<a href="https://colab.research.google.com/github/DiegoF-G/Numpy/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selecionando dados

In [3]:
import numpy as np
# diametro, peso e cores de laranjas e toranjas
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/citrus.csv'
dados = np.loadtxt(url, delimiter=',', usecols=np.arange(1,6,1), skiprows=1)

"""Selecionando diametro (coluna 0) e peso (coluna 1) das laranjas e toranjas,
   da linha 0 a 4999 são laranjas e o restante é das toranjas"""
diameter_orange, weight_orange = dados[:5000, 0], dados[:5000, 1]
diameter_grapefruit, weight_grapefruit = dados[5000:, 0], dados[5000:, 1]
print(f'{diameter_orange}\n{diameter_grapefruit}\n{weight_orange}\n{weight_grapefruit}')


[ 2.96  3.91  4.42 ... 12.55 12.75 12.87]
[ 7.63  7.69  7.72 ... 15.59 15.92 16.45]
[ 86.76  88.05  95.17 ... 218.07 230.13 231.09]
[126.79 133.98 135.56 ... 256.5  260.14 261.51]
